### A Deep Dive into Fashion MNIST with Convolutional Neural Networks (CNN)


**Introduction:**<br>
In the fast-paced world of technology, machine learning and deep learning have become essential tools for solving complex problems and making sense of vast amounts of data. One fascinating application is image recognition, where Convolutional Neural Networks (CNNs) have proven to be remarkably effective. In this blog post, we'll explore the Fashion MNIST dataset and delve into the creation of a CNN model to classify fashion items with high accuracy.



In [1]:
# Example = Fashion Mnist Dataset

#### Steps:
1. Load Dataset
2. EDA
3. Data cleaning 
4. Data Pre processing
5. Apply CNN
6. Deep Neural Network
7. Evaluate the result

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

import tensorflow as tf

In [3]:
# Read Dataset
from tensorflow.keras.datasets import fashion_mnist

In [4]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

| Label | Description |
|:-----:|-------------|
|   0   | T-shirt/top |
|   1   | Trouser     |
|   2   | Pullover    |
|   3   | Dress       |
|   4   | Coat        |
|   5   | Sandal      |
|   6   | Shirt       |
|   7   | Sneaker     |
|   8   | Bag         |
|   9   | Ankle boot  |

In [5]:
(x_train.shape, y_train.shape), (x_test.shape, y_test.shape)

(((60000, 28, 28), (60000,)), ((10000, 28, 28), (10000,)))

In [6]:
x_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [7]:
# Pre Processing 


In [8]:
x_train = x_train/255
x_test = x_test/255

In [9]:
# categorical => One hot encoding

In [10]:
from keras.utils import to_categorical

In [11]:
ytrain = to_categorical(y_train, num_classes=10)

In [12]:
ytest = to_categorical(y_test, num_classes=10)

In [13]:
ytrain

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [14]:
# Build a CNN  model

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten

In [16]:
from tensorflow.keras.layers import BatchNormalization

from tensorflow.keras.optimizers import Adam, Adagrad, RMSprop

##### CNN MODEL

In [17]:
# CNN layer 1  + CNN Layer 2 => Fatten => Hidden Layer 1 + Hidden Layer 2 => Output Layer
# Layer : input data => Convolution with Kernel => Pooling => Flatten

In [18]:
model = Sequential()


In [19]:

# CNN layer 1 

model.add(Conv2D(128, (3,3), activation='relu', input_shape = (28,28, 1), padding = 'valid'))
model.add(MaxPool2D( pool_size= (2,2)))
model.add(Dropout(rate=0.20))

# CNN layer 2 
model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPool2D(pool_size= (2,2)))
model.add(Dropout(rate=0.20))

# CNN layer 3 
model.add(Conv2D(32, (3,3), activation='relu'))
model.add(MaxPool2D(pool_size= (2,2)))
model.add(Dropout(rate=0.20))

# Flatten the data

model.add(Flatten())

# Deep Neural network

#hidden layer

model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.20))

#hidden layer2
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.20))

# output layer 
model.add(Dense(10, activation='softmax'))



In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 128)       1280      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 128)      0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 13, 13, 128)       0         
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        73792     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 dropout_1 (Dropout)         (None, 5, 5, 64)          0

In [21]:
# Compile the Model

model.compile(optimizer='Adam', loss = tf.keras.losses.categorical_crossentropy, metrics= ['accuracy'])

In [22]:
# train the model 

result = model.fit(x_train, ytrain, epochs=10, validation_data= (x_test, ytest))

Epoch 1/10
1875/1875 [==============================] - 192s 101ms/step - loss: 0.7056 - accuracy: 0.7307 - val_loss: 0.4760 - val_accuracy: 0.8219
Epoch 2/10
1875/1875 [==============================] - 192s 102ms/step - loss: 0.5060 - accuracy: 0.8125 - val_loss: 0.4299 - val_accuracy: 0.8410
Epoch 3/10
1875/1875 [==============================] - 188s 100ms/step - loss: 0.4516 - accuracy: 0.8343 - val_loss: 0.3887 - val_accuracy: 0.8550
Epoch 4/10
1875/1875 [==============================] - 181s 96ms/step - loss: 0.4217 - accuracy: 0.8452 - val_loss: 0.3866 - val_accuracy: 0.8576
Epoch 5/10
1875/1875 [==============================] - 175s 94ms/step - loss: 0.4018 - accuracy: 0.8542 - val_loss: 0.3661 - val_accuracy: 0.8638
Epoch 6/10
1875/1875 [==============================] - 180s 96ms/step - loss: 0.3893 - accuracy: 0.8573 - val_loss: 0.3664 - val_accuracy: 0.8645
Epoch 7/10
1875/1875 [==============================] - 176s 94ms/step - loss: 0.3847 - accuracy: 0.8590 - val_loss

In [23]:
# evaluating model  with test image 

In [24]:
#from PIL import Image


In [25]:
#im1 = Image.open('shirt.png')

In [26]:
#im1

In [27]:
# pre process the test image

# 1. convert to grayscale image
# 2. 

In [28]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [29]:
import cv2

In [30]:
im1 = cv2.imread('shirt.png')

In [31]:
# convert color to grayscale


In [32]:
im1_g = cv2.cvtColor(im1, cv2.COLOR_BGR2GRAY)

In [33]:
# Resize(120 X  135) Image to (28 X 28) pix

In [34]:
im1_new = cv2.resize(im1_g, ([28,28]))


In [35]:
# change dimnesion
im1_new = np.expand_dims(im1_new, axis = 0)
im1_new.shape

(1, 28, 28)

In [36]:
#im1_new = np.array(im1_new)

In [37]:
#predict the result

In [41]:
res = model.predict(im1_new)

1/1 [==============================] - 0s 45ms/step


In [42]:
res

array([[7.0901483e-01, 4.9792214e-33, 2.9098520e-01, 2.0872216e-21,
        1.7288019e-12, 0.0000000e+00, 1.6693124e-19, 0.0000000e+00,
        3.4353009e-16, 0.0000000e+00]], dtype=float32)

In [40]:
classlabels = {0:'T-shirt/top',1:'Trouser',2:'Pullover',3:'Dress',4:'Coat',5:'Sandal',6:'Shirt',7:'Sneaker',8:'Bag',9:'Ankle boot'}

In [45]:
max_index = np.argmax(res) 
print(max_index)

0


In [46]:
for i in range(0,10):
    if i == max_index:
        print("The classlabel for the given image is ", classlabels[i])

The classlabel for the given image is  T-shirt/top


In [ ]:
Conclusion:
The MNIST project with deep learning encapsulates the essence of image classification using neural networks. From the initial data collection to the intricate process of model building, training, and testing, each step contributes to the model's ability to recognize and classify handwritten digits. As we navigate the complexities of digit recognition, the MNIST project exemplifies the transformative potential of deep learning in the realm of artificial intelligence. The fusion of data science and neural networks in projects like MNIST paves the way for advancements in image recognition, shaping the future of technology.